version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Ñ‘
      POSTGRES_PASSWORD: postgres_28hw
      POSTGRES_DB: postgres_28hw
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data:
